### ISSUE TITLE
Testing uxnds on iphone Delta

### ISSUE THREAD

**Issue by nixoye** [asiekierka/uxnds#1]
I installed Delta from the altsore to get a nintendo DS emulator running on my non jailbroken iphone. I'm trying to test uxnds and after running the uxnds_debug I get `Error FAT init: Failed`

**Comment by asiekierka** [comment]
Yes, correct. Your NDS emulator does not emulate a memory card-providing device (like a flashcart), which means uxnds has nowhere to read the ROMs from. Most emulators don't really have an user-friendly way to set one up that works with modern homebrew, either (I think DesMuMe *might*? But I never got it to work myself).

In general, using an NDS emulator just to run Uxn on an iPhone feels a bit silly - I'd recommend working on a native Uxn port.
