### ISSUE TITLE
No longer runs launcher.rom on DSi

### ISSUE THREAD

**Issue by jahnertz** [asiekierka/uxnds#11]
Crashes with ```Halted: Working-stack underflow#0038, at 0x05c3``` when loading launcher.rom on DSi hardware
<details>
<summary>launcher.rom on uxnds 0.3.4:</summary>
<img alt="launcher.rom on 0.3.4" src="https://user-images.githubusercontent.com/12776127/170807087-7223c8bf-30e9-4930-83a9-cc0982b0edc7.jpg" />
</details>
<details>
<summary>launcher.rom on uxnds 0.3.5:</summary>
<img alt="launcher.rom on 0.3.5" src="https://user-images.githubusercontent.com/12776127/170807083-d5f7e076-6f2e-47d1-aa33-53849d933e6f.jpg" />
</details>

**Comment by asiekierka** [comment]
Did you update your launcher.rom in line with the CPU opcode changes?

**Comment by jahnertz** [comment]
Aha – yep, the latest version from the uxn repo works fine. Thanks!
