### ISSUE TITLE
Keyboard shortcuts not working [CTRL button]

### ISSUE THREAD

**Issue by shawnpinciara** [asiekierka/uxnds#12]
The possibility to save and perform other necessary actions to control all the roms is disabled, as the CTRL button on the keyboard doesn't allow for shortcuts

**Comment by zzo38** [comment]
Some programs use the joypad A button in combination with letter keys; try that. You might also be able to select those commands from the menu.

**Comment by asiekierka** [comment]
Resolved in uxnds 0.4.0 with a new keyboard implementation.
