### ISSUE TITLE
NDS lite graphics not working well with 0.3.5 version

### ISSUE THREAD

**Issue by craigcomstock** [asiekierka/uxnds#13]
Using latest 0.3.5 release with DS One loader (not sure about this exactly, which version and such).

Previously graphics were working mostly, just file select was broken I think.

With this version the graphics seems mostly blank with just a few pixels drawn.

On start I get Halted: Working-stack underflow#0030, at 0x053b and not much more can be done.

This is using uxnds_debug.nds.

If I use the uxnds.nds I get a bit more of the screen drawn and see some changes when tapping on the touchscreen device.

I did reload the uxn roms from https://rabbits.srht.site/uxn/uxn-essentials-mac64.zip just now and that didn't seem to change things, thought maybe there was some API change or something causing the stack problem.

**Comment by craigcomstock** [comment]
checked and 0.3.4 version works graphics wise :+1: piano.rom works so not terribly broken there :)

**Comment by craigcomstock** [comment]
Did a lot of opcodes change numbers maybe? I saw quite a lot of change in the diff between 0.3.4 and 0.3.5 I think.

Thanks for the reset uxnds feature by pressing both start+select buttons! Makes switching real nice!

**Comment by asiekierka** [comment]
I was told to update uxn opcodes to the latest version of the spec...

**Comment by craigcomstock** [comment]
> I was told to update uxn opcodes to the latest version of the spec...

Right on. Makes sense. I guess I need to re-make my roms from sources with the latest uxnasm. Will try that, bet it'll work! Thanks!
