### ISSUE TITLE
Uxn core to make use of extraneous 3 opcodes

### ISSUE THREAD

**Issue by neauoire** [asiekierka/uxnds#14]
The new uxn specs is making use of the 3 free opcodes (0x20, 0x40 and 0x60), see [refs](http://wiki.xxiivv.com/site/uxntal_reference.html) to basically addsrelative immediate jumps.

```
case 0x20: /* JCI */ POP8(b) if(!b) { pc += 2; break; }
case 0x40: /* JMI */ PEEK16(a, pc) pc += a + 2; break;
case 0x60: /* JSI */ PUSH16(u->rst, pc + 2) PEEK16(a, pc) pc += a + 2; break;
```

See [example implementation](https://git.sr.ht/~rabbits/uxn/tree/main/item/src/uxn.c#L53). There aren't many roms that make use of this yet, it'll roll out slowly during the next few months. But [left.rom](https://rabbits.srht.site/left/left.rom) does use the new opcodes, so if anything shows up then it's a good sign.

**Comment by asiekierka** [comment]
https://github.com/asiekierka/uxnds/releases/tag/v0.3.6
