### ISSUE TITLE
how do i actually install this on my 3ds?

### ISSUE THREAD

**Issue by EanimeiCCC** [asiekierka/uxnds#15]
how do i actually install this on my 3ds? i have no idea how to do that but I really want to.

**Comment by LordRembo** [comment]
@EanimeiCCC There's 2 ways to run homebrew applications like this: either using a flashcartridge (R4 and all kinds of copies/clones/variants) or by hacking the 3DS so you can put it on the SD-card.
There is a 'flashcarts' reddit which has a nice overview of cartridges you can get (the AliExpress ones are cheap and will do the job), but if you really want to get the full potential of your 3DS (eg. install other homebrew apps or games), you should search for '3DS Hacks Guide' and follow that. Takes more time though, and has some risk to it.
- on flashcart: put the `.nds` application in the root of the card along with the `uxn` folder. When you turn on your 3DS, you'll be able to see your flashcart just like you would see the icon of a game that is inserted. When opening that, you'll see the uxn application and you can open that up.
- on a hacked 3DS: you'll need to install 'Twilight ++', this is an application which can run DS applications and games. After completing the hacking guide, you'll have 1 or more applications that are sort of stores for homebrew applications. They will have it listed so you can simply click and install it.

**Comment by asiekierka** [comment]
For 3DS users, I recommend installing [nds-hb-menu](https://github.com/devkitPro/nds-hb-menu/releases) over TWLMenu++ at this time, as the latter includes DRM circumvention game patches and other features which may be legally dubious in some jurisdictions, and are besides only useful for running pirated games. It's also a 40MB+ install versus, like, a few hundred kilobytes, and takes longer to boot...

I'd also like to provide a native version of uxnds for the 3DS at some point, due to its higher CPU speeds and display resolution.

**Comment by EanimeiCCC** [comment]
> @EanimeiCCC There's 2 ways to run homebrew applications like this: either using a flashcartridge (R4 and all kinds of copies/clones/variants) or by hacking the 3DS so you can put it on the SD-card. There is a 'flashcarts' reddit which has a nice overview of cartridges you can get (the AliExpress ones are cheap and will do the job), but if you really want to get the full potential of your 3DS (eg. install other homebrew apps or games), you should search for '3DS Hacks Guide' and follow that. Takes more time though, and has some risk to it.
> 
> * on flashcart: put the `.nds` application in the root of the card along with the `uxn` folder. When you turn on your 3DS, you'll be able to see your flashcart just like you would see the icon of a game that is inserted. When opening that, you'll see the uxn application and you can open that up.
> * on a hacked 3DS: you'll need to install 'Twilight ++', this is an application which can run DS applications and games. After completing the hacking guide, you'll have 1 or more applications that are sort of stores for homebrew applications. They will have it listed so you can simply click and install it.

which store is it in? i couldn't seem to find it.

**Comment by LordRembo** [comment]
@EanimeiCCC You should be able to find both HBmenu and TWiLight Menu++ using the `Universal Updater` application.

**Comment by EanimeiCCC** [comment]
> @EanimeiCCC You should be able to find both HBmenu and TWiLight Menu++ using the `Universal Updater` application.

so I managed to get the thing on it put I still can't seem to get it to work. i put the uxnds file in and it opens but it's just blank

**Comment by LordRembo** [comment]
@EanimeiCCC When using uxnds_debug.nds or uxnds_profile.nds, what error or warning do you get?

**Comment by EanimeiCCC** [comment]
> @EanimeiCCC When using uxnds_debug.nds or uxnds_profile.nds, what error or warning do you get?

nothing, I think I got it mostly working now though. the screen on the top is cutting off some and it won't let me go back to the menu properly for some reason
