### ISSUE TITLE
Support relative path and RomFS "boot.rom" locations.

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/uxnds#18]

**Comment by farvardin** [comment]
the documentation is quite clear that the uxn folder should be in "/uxn" but generally people put their .3dsx files into a special folder (mine is /3ds), therefore if we put uxn inside it (/3ds/uxn) it won't work. Relative path would be great :)

**Comment by farvardin** [comment]
btw should it be active in the latest release? It didn't work for me. Maybe the uxnds app should be inside the uxn folder then? I'll test this anyway...
