### ISSUE TITLE
D-pad/Joystick double-triggers input

### ISSUE THREAD

**Issue by DeltaF1** [asiekierka/uxnds#19]
In the boot rom I am unable to select some options because a press of the d-pad (or movement on joystick) moves two spaces in the list, one on button down and one on button up. Same problem in orca.

Just tested and it's the same for the NDS or 3DS versions. (I'm running both on a N3DSXL if that matters)

**Comment by DeltaF1** [comment]
Nevermind, I missed the .a release which fixes this. Good timing!

**Comment by asiekierka** [comment]
Sorry, I hoped nobody would notice... ^^
