### ISSUE TITLE
Uxnds 3DS crashes on startup on Old Nintendo 3DS [Fix]

### ISSUE THREAD

**Issue by RE4PERX6** [asiekierka/uxnds#22]
Usually, when homebrew is installed in the 3ds, it goes to the /3ds folder, which is the one that **the homebrew launcher** has assigned by default, but when trying to start it from there, the screen stays black and the bottom screen shows an error message, then if you do not press start to return to homebrew launcher the console crashes and creates an error code, and then it turns off.

- My solution was to take the executable "**uxnds.3dsx**" to the root of the sd card and paste it next to the "**unx**" rom folder in this way when executed it goes directly to the launcher as expected and from a very uneducated opinion it seems that everything works as it should from that point on.

**Comment by asiekierka** [comment]
I cannot reproduce this error, sorry.

**Comment by RE4PERX6** [comment]
After reviewing better, apparently the roms folder is the only one that should go to the root folder of the _SD_, the executable can run inside the homebrew menu folder without problems _[/SD/3DS]_, I was wrong in thinking that I had to put both files in the same folder since there is homebrew that creates subfiles in the root of the SD while the executable is in _/3DS_ as rehid for example.

I think that would explain the error message and crashes since I couldn't open launcher.rom because it was not in the correct path.

That would conclude the thread and it could be considered solved i guess.

Thanks for your time and interest. 🙏🤍

**Comment by asiekierka** [comment]
https://github.com/asiekierka/uxnds/issues/25 Might be fixed. I didn't realize people put the `uxn` folder alongside `uxnds.3dsx`.
