### ISSUE TITLE
Missing input rom error on DSi SD (FIXED)

### ISSUE THREAD

**Issue by DankMemes2005** [asiekierka/uxnds#25]
![IMG_20231123_161956](https://github.com/asiekierka/uxnds/assets/151880333/3d2d0e70-aa79-45e9-992d-630e1096350a)
I have confirmed the rom does exist its just not finding it.
the path to the rom is (root/Apps/unxDS/unx/boot.rom)

**Comment by DankMemes2005** [comment]
FIXED unx folder has to be in roos of SD card

**Comment by asiekierka** [comment]
This layout should be fixed in https://github.com/asiekierka/uxnds/commit/7fb9120b6af38d679d63f8d82d9509817afd2ea4
