### ISSUE TITLE
Some roms only show part of the program on screen

### ISSUE THREAD

**Issue by DankMemes2005** [asiekierka/uxnds#26]
### **_(I am using a dsi xl with twilightmenu++ and unlaunch)_**

first program that does this is BOOT.rom
![IMG_20231123_232948](https://github.com/asiekierka/uxnds/assets/151880333/57449956-5f17-45de-9128-75f12b8d8f6a)
second program that does this is turye.rom
![IMG_20231123_233140](https://github.com/asiekierka/uxnds/assets/151880333/393ee277-e873-4d3a-87fc-caa769d0b692)
asma.rom doesn't work at all
![IMG_20231123_233523](https://github.com/asiekierka/uxnds/assets/151880333/a41fdde4-9588-4e52-970b-644c6f7ab6f5)
the next rom is left.rom
![IMG_20231123_233704](https://github.com/asiekierka/uxnds/assets/151880333/413fdb93-5703-4a57-a398-3e83c622e925)
the next rom is nasu.rom
![IMG_20231123_233846](https://github.com/asiekierka/uxnds/assets/151880333/8efc4f22-3bd2-414d-890b-eac73e49f4c7)

**Comment by asiekierka** [comment]
Yes, that's normal. A lot of uxn programs are written for a 320x240 screen at minimum, and aren't properly adapted for the DS's 256x192 resolution.

`asma.rom` requires a command line argument to assemble a file, IIRC, which is not of too much use in a DS/DSi context.
