### ISSUE TITLE
Clock doesn't keep ticking

### ISSUE THREAD

**Issue by DeltaF1** [asiekierka/uxnds#3]
The datetime device gets the correct time when the program starts, but then doesn't update the time afterwards.

Running on melonDS produces the following status message on boot:
```
RTC INTERRUPT ON: 41
```

[libdns ties the real time clock update to the network interrupt handler](https://github.com/devkitPro/libnds/blob/154a21cc3d57716f773ff2b10f815511c1b8ba9f/source/arm7/clock.c#L274). Is it possible that that's being overwritten/disabled somewhere in your code?

**Comment by neauoire** [comment]
Any update on this?

**Comment by asiekierka** [comment]
*Might* be fixed in uxnds 0.3.4.

**Comment by DeltaF1** [comment]
Works on my DSL :)
