### ISSUE TITLE
"Empty Folder" on NDS (uxnds filesystem bug?)

### ISSUE THREAD

**Issue by craigcomstock** [asiekierka/uxnds#6]
I have booted up with hbmenu, put launcher.rom as uxn/boot.rom on my sdcard in a DSONE clone flash cart.

I get a nice debug display that keeps updating on one screen and the character logo + "0/0" and "Empty Folder" on the other screen. I placed many .rom files in uxn/ on the sdcard.

I tried moving the rom files to uxn/uxn/ and also the root, /, out of curiosity but that didn't change the behavior.

I tried booting the uxnds_debug directly instead of with hbmenu, same behavior.

I copied piano.rom from uxn build to uxn/boot.rom and that starts and works, makes noise etc :+1:

Seems like this might be a bug in uxnds file system implementation? Since the roms basically work just can't see the rom files in uxn/

I think this is where the message comes from:
https://git.sr.ht/~rabbits/uxn/tree/main/item/projects/software/launcher.tal#L307

**Comment by craigcomstock** [comment]
Maybe make another release? I was using 0.3.3 and it didn't work, then installed devkit, rebuilt and works! And I can see that the needed code isn't in 0.3.3 but in main: https://github.com/asiekierka/uxnds/compare/v0.3.3...main

**Comment by DeltaF1** [comment]
Yes I added the directory-loading code relatively recently and I don't think asie has made a release since then.

**Comment by asiekierka** [comment]
Fixed in uxnds 0.3.4.

**Comment by craigcomstock** [comment]
> Fixed in uxnds 0.3.4.
Thanks! I'll test it out, certain it will work. :)
