### ISSUE TITLE
Uxn stack opcodes order changed

### ISSUE THREAD

**Issue by neauoire** [asiekierka/uxnds#9]
This change was added to help with the drop/roll/pick microcode implementation and as to follow the machineforth order:

![image](https://user-images.githubusercontent.com/1455726/169914559-37291b33-b499-4b69-bcbe-b657d011f058.png)

The only thing that changes is the order of the opcodes, the uxngba port uses a very similar [uxn.c](https://git.sr.ht/~rabbits/uxn-gba/tree/main/item/src/uxn.c) file to yours, I'm not sure if it's just a matter of copy/pasting it.

This is possibly the last change to the uxn core, ever.

**Comment by asiekierka** [comment]
https://github.com/asiekierka/uxnds/commit/6eb64c15c6c3e1ab330a2dd62abcfe3bb660e1e6

**Comment by neauoire** [comment]
cheers ^^
